# Generated by Django 3.2.9 on 2021-11-22 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=16)),
                ('rg', models.CharField(max_length=24)),
                ('endereco', models.CharField(max_length=240)),
                ('instituicao_ensino', models.CharField(max_length=80)),
                ('curso', models.CharField(max_length=80)),
                ('saldo', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('cpf', models.CharField(max_length=16)),
                ('departamento', models.CharField(max_length=80)),
                ('instituicao_ensino', models.CharField(max_length=80)),
                ('saldo', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vantagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField()),
                ('foto', models.CharField(blank=True, default='', max_length=360, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coin_system.empresa')),
            ],
        ),
    ]
