# Generated by Django 3.2.9 on 2021-12-05 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coin_system', '0002_auto_20211130_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='vantagem',
            name='valor',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coin_system.aluno')),
                ('professor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='coin_system.professor')),
                ('vantagem', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='coin_system.vantagem')),
            ],
        ),
    ]
