# Generated by Django 3.2.9 on 2021-12-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_system', '0003_auto_20211205_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='valor',
            field=models.IntegerField(default=0),
        ),
    ]
